# Password to enter with /pw <password>.
password: passwort

#Permission to deny the /pw command.
#May use for groups higher than the group that shall use the password.
permission_deny: pwgroup.deny

#List of groups that the player will be added to.
groups:
  - user

#Message you get if you have the permission_deny.
message_deny: "§4You may not enter this command."

#Message you get after entering the correct password.
message_success: "§aYou have successfully entered the password."

#Message you get if you enter the wrong password.
message_wrong: "§cYou have entered a wrong password."

#Message you get if not entered by a player.
message_user: "§cOnly players may use the /pw command."
