name: PasswordGroup
main: de.selebrator.pwgroup.Main
version: 1.1.0-beta
authors: [Selebrator]
depend: [Vault]
commands:
  password:
    aliases:
      - pw
      - passwort
    usage: |
           /<command> <password>
permissions:
  password.notify.*:
    description: Get notified when a player enters a password regardless of correctness
    children:
      password.notify.success: true
      password.notify.wrong: true
  password.notify.sucess:
    description: Get notified when a player enters the correct password
  password.notify.wrong:
    description: Get notified when a player enters an incorrect password